### PR TITLE
Completing work for 14393 analysis

### PR DESCRIPTION
**Pull request by brandonh-msft**
- Bumped the `nupkg` version
- Made analyzer spit out more useful warnings (eg: **what** version a call is specific to)
- Update Demo apps with analyzer and 14393-specific calls to illustrate the warnings for 14393

### CODE REVIEW

**Comment by quincycs** [comment]
Excited for this to be updated! :)

**Comment by quincycs** [comment]
@brandonh-msft do you know the plan to getting this nuget package updated?  happy to use a new nuget package that you publish.   Ideally MSFT supports this for xaml/c#  apps going in the future.

**Comment by brandonh-msft** [comment]
unfortunately I do not. The onus is on @ljw1004 to pull my req in to the nupkg and update the listing

**Comment by ljw1004** [comment]
Oh boy I'm sorry about this Brandon. I left Microsoft at the start of October and this PR got lost in the turmoil.

Someone from the relevant Microsoft team, "Vladimir Postel", is taking over this project. It will be moved into the official Microsoft Git. I wonder if you could email his corp address directly and figure out what is the status on that and how to contribute?

(I worry that if I accept this PR here and now, it might not make it into his version. Once he's moved it then I'm going to close up this repo.)

**Comment by brandonh-msft** [comment]
np @ljw1004. I've been in contact w/ Vladimir recently and he filled me in on this new process. He's also seen my PR. I'm sure it'll all be resolved in due time.

**Comment by quincycs** [comment]
Ok thx.  I'll ping again this after a couple months. 💀

**Comment by dotMorten** [comment]
@vladimp Any update on the status of this?

**Comment by quincycs** [comment]
This needs to be updated for creators update also

**Comment by quincycs** [comment]
@vladimp soon would be updated with fall creators update.  Any hope in the future? 😑

**Comment by taoyouh** [comment]
@brandonh-msft How's this project going? Creator's update and fall creator's update has come and this project is silent.

**Comment by brandonh-msft** [comment]
@taoyouh I'm not a maintainer here, just submitted a PR...

The community at large is waiting to hear from @terrajobst as to whether or not this project will live on as his [dotnet\platform-compat](https://github.com/dotnet/platform-compat) repo

**Comment by brandonh-msft** [comment]
closing due to inaction

**Pull request closed without merging**
